version: '3'

services:
    app:
      container_name: devops-container
      #build: . 로컬에서 빌드
      # image 방식은 허브에 있는 이미지 docker desktop에서 가져오기
      image: seokhun0906/devopsapp:ver1.0
      depends_on:
              - database
      ports:
        - "8888:7777"
      environment:
        SPRING_DATASOURCE_URL: jdbc:mariadb://database:3306/test_db
        SPRING_DATASOURCE_USERNAME: tester
        SPRING_DATASOURCE_PASSWORD: test1234
      restart: always
                
    database:
          image: mariadb:10.6.16
          container_name: spring-db
          environment:
                MARIADB_ROOT_PASSWORD: 123456789
                MARIADB_USER: tester
                MARIADB_PASSWORD: test1234
                MARIADB_DATABASE: test_db
          volumes:
            - ./src/main/resources/db_config/initdb.d:/docker-entrypoint-initdb.d
          ports:
              - "6033:3306"
          
          