server:
  port: 7777


# DB property Setting 
spring:
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://localhost:6033/test_db
        username: tester
        password: tester1234

mybatis:
      mapper-locations: classpath:mappers/*.xml